// <auto-generated />
namespace Sistemacompras.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class up6 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(up6));
        
        string IMigrationMetadata.Id
        {
            get { return "202002170020578_up6"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
