// <auto-generated />
namespace Sistemacompras.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class up4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(up4));
        
        string IMigrationMetadata.Id
        {
            get { return "202002161926178_up4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
